### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by haesleinhuepf** [fadero/deskew_rotate_OPMstack#1]
Hi Tanner @fadero ,

this is an amazing resource! Thanks for sharing openly! I was just wondering under which conditions one could reuse the code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by fadero** [comment]
Thanks for the reminder @haesleinhuepf– I've updated the README and added a license file in the main branch. It's CC 4.0! Hopefully this is useful. 

And thank you for making CLIJ2 so accessible!
